# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/BuildingBlocks',
                'doc_host': 'https://teja00.github.io',
                'git_url': 'https://github.com/teja00/BuildingBlocks',
                'lib_path': 'BuildingBlocks'},
  'syms': {'BuildingBlocks.core': {'BuildingBlocks.core.foo': ('core.html#foo', 'BuildingBlocks/core.py')}}}
