# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/BuildingBlocks',
                'doc_host': 'https://teja00.github.io',
                'git_url': 'https://github.com/teja00/BuildingBlocks',
                'lib_path': 'BuildingBlocks'},
  'syms': { 'BuildingBlocks.matrix_vector_dot_product': { 'BuildingBlocks.matrix_vector_dot_product.matrix_dot_vector': ( 'matrix_vector_dot_product.html#matrix_dot_vector',
                                                                                                                          'BuildingBlocks/matrix_vector_dot_product.py')},
            'BuildingBlocks.mean_row_column': { 'BuildingBlocks.mean_row_column.calculate_matrix_mean': ( 'mean_by_row_column.html#calculate_matrix_mean',
                                                                                                          'BuildingBlocks/mean_row_column.py')},
            'BuildingBlocks.reshape_matrix': { 'BuildingBlocks.reshape_matrix.reshape_matrix': ( 'reshape_matrix.html#reshape_matrix',
                                                                                                 'BuildingBlocks/reshape_matrix.py')},
            'BuildingBlocks.transpose_matrix': { 'BuildingBlocks.transpose_matrix.transpose_matrix': ( 'transpose_of_matrix.html#transpose_matrix',
                                                                                                       'BuildingBlocks/transpose_matrix.py')}}}
