"""This is a python Function that computes the dot product of a matrix and a vectors"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_matrix_vector_dot_product.ipynb.

# %% auto 0
__all__ = ['matrix_dot_vector']

# %% ../nbs/00_matrix_vector_dot_product.ipynb 2
from typing import List, Optional, Tuple, Union

# %% ../nbs/00_matrix_vector_dot_product.ipynb 5
def matrix_dot_vector(a: List[List[Union[int, float]]], b: List[Union[int, float]]) -> List[Union[int, float]]:
	# Return a list where each element is the dot product of a row of 'a' with 'b'.
	# If the number of columns in 'a' does not match the length of 'b', return -1.
    if not all(len(row) == len(b) for row in a):
        return -1
    result = []
    for row in a:
        dot = sum(x * y for x, y in zip(row, b))
        result.append(dot)
    return result
