"""This is a python Function that computes the dot product of a matrix and a vector"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_matrix_vector_dot_product.ipynb.

# %% auto 0
__all__ = ['matrix_dot_vector']

# %% ../nbs/00_matrix_vector_dot_product.ipynb 2
from typing import List, Optional, Tuple, Union

# %% ../nbs/00_matrix_vector_dot_product.ipynb 4
def matrix_dot_vector(a: List[List[Union[int, float]]] # Matrix ' a' of size m x n
                      , b: List[Union[int, float]] # Vector ' b' of size n x 1
                      ) -> List[Union[int, float]]: # Resulting vector of size m x 1:
    if not all(len(row) == len(b) for row in a):
        return -1
    result = []
    for row in a:
        dot = sum(x * y for x, y in zip(row, b))
        result.append(dot)
    return result
