"""Writing a Python function that calculates the inverse of a 2x2 matrix. Return 'None' if the matrix is not invertible."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_matrix_inverse.ipynb.

# %% auto 0
__all__ = ['inverse_2x2']

# %% ../nbs/08_matrix_inverse.ipynb 3
from typing import List, Union
import numpy as np
from .matrix_scalar_multiply import *

# %% ../nbs/08_matrix_inverse.ipynb 4
def inverse_2x2(matrix: list[list[float]] # matrix to be inverted size (2, 2)
				) -> list[list[float]]: # inverse of the matrix
	matrix = np.array(matrix)
	a, b, c, d  = matrix.flatten()
	det = a*d - b*c
	if det == 0:
		return None
	adj_matrix = np.array([[d, -b], [-c, a]])
	inverse = matrix_scalar_multiply_numpy(1/ det, adj_matrix)
	return inverse
