"""python function to calculate the mean of a matrix either by row or by column"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Matrix/Statistics/03_mean_by_row_column.ipynb.

# %% auto 0
__all__ = ['calculate_matrix_mean']

# %% ../nbs/Matrix/Statistics/03_mean_by_row_column.ipynb 2
from typing import List, Union
import numpy as np

# %% ../nbs/Matrix/Statistics/03_mean_by_row_column.ipynb 3
def calculate_matrix_mean(	matrix: list[list[Union[int, float]]], # Matrix of size m, n
                        	mode: str # representing column or row
						  ) -> list[Union[int, float]]: # result of size m, 1 or n, 1
    matrix = np.array(matrix)
    
    if mode == "row":
        means = [np.mean(row) for row in matrix]
    else:  # assume column mode
        means = [np.mean(matrix[:, i]) for i in range(matrix.shape[1])]
    
    return means
