"""Python Function that computes the Reshaping of a matrix"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_reshape_matrix.ipynb.

# %% auto 0
__all__ = ['reshape_matrix']

# %% ../nbs/02_reshape_matrix.ipynb 2
from typing import List, Union
import numpy as np

# %% ../nbs/02_reshape_matrix.ipynb 4
def reshape_matrix( a: List[List[Union[int, float]]], # matrix a of size (m, n) of int or float
                    new_shape: tuple[int, int] # new shape tuple to reshape into (a, b)
                    ) -> list[list[Union[int,float]]]: # output matrix of shape (a, b)
    flat = np.array(a).flatten()

    # Validate the reshape is possible
    if len(flat) != new_shape[0] * new_shape[1]:
        return []

    # Manually reshape using slicing
    reshaped_matrix = [
        flat[i * new_shape[1] : (i + 1) * new_shape[1]].tolist()
        for i in range(new_shape[0])
    ]

    return reshaped_matrix
