"""This is a python Function that computes the transpose of a matrix"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_transpose_of_matrix.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01_transpose_of_matrix.ipynb 2
from typing import List, Union
